/var/spool/slurmd/job41654/slurm_script: line 8: activate: No such file or directory
Which device
4
Script used: train_downstream.py
Config path conf/supervised_tasks/enhancer_annotation/
/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484808560/work/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Run experiment
[2023-06-13 12:50:51,091][HYDRA] Launching 1 jobs locally
[2023-06-13 12:50:51,091][HYDRA] 	#0 : ++data.partition_split=1
output_dir /z/home/frma/projects/DNA-LM/test/
device cpu
Error executing job with overrides: ['++data.partition_split=1']
Traceback (most recent call last):
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/_internal/utils.py", line 635, in _locate
    obj = import_module(part0)
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'models'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/_internal/utils.py", line 637, in _locate
    raise ImportError(
ImportError: Error loading 'models.downstream.CNN':
ModuleNotFoundError("No module named 'models'")
Are you sure that module 'models' is installed?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nfs/home/frma/projects/BEND/scripts/train_downstream.py", line 72, in <module>
    run_experiment()
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/_internal/utils.py", line 465, in _run_app
    run_and_report(
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/_internal/utils.py", line 222, in run_and_report
    raise ex
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/_internal/utils.py", line 219, in run_and_report
    return func()
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 182, in sweep
    _ = r.return_value
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/nfs/home/frma/projects/BEND/scripts/train_downstream.py", line 35, in run_experiment
    model = hydra.utils.instantiate(cfg.model).to(device).float()
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/z/home/frma/lib/software/miniconda3/envs/torch-p310/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'models.downstream.CNN', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model
